title: Gary Zhu
logo: /assets/img/IMG8662.jpg
email: Garyzhu19@gmail.com
description: 
show_downloads: false
google_analytics: UA-108144808-1
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Linkedin
    link: https://www.linkedin.com/in/zhu-gary/
  - name: Resume
    link: https://garyzhu19.github.io/online-cv/

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error —
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
#github: [metadata]
